### ISSUE TITLE
Render error on Windows 10 x64

### ISSUE THREAD

**Issue by petrepopescu21** [faressoft/terminalizer#1]
I've successfully installed the package after setting up node-gyp and successfully recorded a session, however, the render command fails almost instantly:

![image](https://user-images.githubusercontent.com/6200656/43119590-b02ed422-8f1f-11e8-9899-4c218d608dd5.png)

**Comment by faressoft** [comment]
Have end the recording session before start the rendering? Please try play command too to check the output

**Comment by petrepopescu21** [comment]
Playing works and the YML file is there. I've stopped the recording with "exit".

**Comment by faressoft** [comment]
Cool, it seems a bug I feel that I know the reason. Will be fixed within 2 hours.

**Comment by petrepopescu21** [comment]
Looking forward to it

**Comment by petrepopescu21** [comment]
I've commented out line 17 out of render/index.js and now it works:
```js
//app.dock.hide();
```

It seems that you'd have to verify the OS before hiding the Dock.

**Comment by faressoft** [comment]
@petrepopescu21 the fix is released, please update your package and confirm that it is fixed

**Comment by petrepopescu21** [comment]
Perfect!
