### ISSUE TITLE
Can't render

### ISSUE THREAD

**Issue by AllanOricil** [faressoft/terminalizer#110]
Everything looks good. I can run `terminalizer init`, `terminalizer config`, `terminalizer record testing`, but `terminalizer render testing` does not work!. I had the sequence of errors below fixed one by one until I got to one that seems it can't be fixed. Could you help to understand why electron displays
`Error: /usr/local/lib/node_modules/terminalizer/node_modules/electron/dist/electron: /lib/x86_64-linux-gnu/libdbus-1.so.3:` on a VM?

The first error right after trying to render for the first time:
![image](https://user-images.githubusercontent.com/55927613/83282438-7e742880-a1d1-11ea-8df1-3b51a365bba1.png)

To fix it, I installed libnss3-dev.

Installing libnss3-dev
![image](https://user-images.githubusercontent.com/55927613/83284760-11fb2880-a1d5-11ea-8df0-75718ad995cf.png)

Then I ran the render command again and now the libXss was missing. Then I installed it too.

Installing libXss
![image](https://user-images.githubusercontent.com/55927613/83284703-fabc3b00-a1d4-11ea-8f8e-bd714d1cc224.png)

Then I got this error that I can't fix :/
![image](https://user-images.githubusercontent.com/55927613/83284648-e710d480-a1d4-11ea-8086-fb203ba13fb9.png)

**Comment by AllanOricil** [comment]
I learned it is an electron issue. It can't work on headless machines.

**Comment by takanotume24** [comment]
Hello .
I had a similar problem with wsl2.
In the end, the render command isn't working (no files are generated when I run it), but I seem to have resolved the dependencies.
#121

**Comment by AllanOricil** [comment]
> Hello .
> I had a similar problem with wsl2.
> In the end, the `render` command isn't working (no files are generated when I run it), but I seem to have resolved the dependencies.
> #121

@takanotume24 I think I installed all the dependencies too, but did not work. Then I started to use it on my windows. I was trying to run it on a VM inside windows and the error appeared.

**Comment by giggio** [comment]
I'm having the same issue mentioned in #121, `terminalizer render demo` simply exits without any messages. I'm also on WSL2. @takanotume24 were you able to solve the issue?

**Comment by AllanOricil** [comment]
> WSL2.

@giggio there is no way to solve it. If you search in the electron repo you will see that this error occurs when running electron in headless mode, like in a vm/WSL2/container.

**Comment by giggio** [comment]
So maybe when WSL2 has desktop support it'll work.
I was able to render on Windows.

**Comment by AllanOricil** [comment]
> So maybe when WSL2 has desktop support it'll work.
> I was able to render on Windows.

yes, on windows everything render without a problem.
