### ISSUE TITLE
TypeError: Cannot read property 'SOCKET' of undefined

### ISSUE THREAD

**Issue by poloka** [faressoft/terminalizer#115]
Upon new install, I attempt to run the command within my Terminal
```
terminalizer record foo
Error:
  TypeError: Cannot read property 'SOCKET' of undefined

Hint:
  Use the --help option to get help about the usage
```

What configuration am I missing?

**Comment by poloka** [comment]
I was using 8.9.4 and it did not work.  updated to use 10.20.1 and I got it to work.

**Comment by eabase** [comment]
@poloka  `10.20.1` of What??
