### ISSUE TITLE
Cannot render X if folder X already exists.

### ISSUE THREAD

**Issue by jukefr** [faressoft/terminalizer#12]
Hello,

I don't know if this is intended but when I record X, then try to render X, if a folder is already present in the current directory with name X it spits out 
```
Error:                                                                                              
  Error: EISDIR: illegal operation on a directory, read
```

Here is a demo : https://asciinema.org/a/G9H5vekzN2rFdfUfJMGNYtJDL

**Comment by abhranil08** [comment]
I want to work on this issue. Please provide more details.

**Comment by jukefr** [comment]
Simply add a check to see if the desired filename is already present as a directory

**Comment by jukefr** [comment]
or maybe simply assume `.yml` is implied for the source argument for the read this way it won't read

**Comment by faressoft** [comment]
I've been working on this, it is now released.

**Comment by faressoft** [comment]
@jukefr I just want to let you know that https://terminalizer.com is released and ready to share your recordings :D
