### ISSUE TITLE
Feature request: How do I know I'm "playing" a demo?

### ISSUE THREAD

**Issue by nampp** [faressoft/terminalizer#17]
I want to be noticed when I'm using 'terminalizer play'.
For example, there could be an inspection before the prompt when playing something like:

```bash
<playing>[root@localhost ~]# mkdir demo
<playing>[root@localhost ~]# cd demo
<playing>[root@localhost ~]# logout
```
Therefor I'll know now it's palying, and I'm not taking control of it.

**Comment by faressoft** [comment]
We can't do that for couple of reasons:

- It is even more confusing since it seems to be part of the recorded frames.
- Terminalizer provides the ability to use other commands than `bash` or non-shell command line app.s
