### ISSUE TITLE
Issue installing on CentOS

### ISSUE THREAD

**Issue by b-yond** [faressoft/terminalizer#18]
![image](https://user-images.githubusercontent.com/26074850/44422558-78a7d880-a551-11e8-9117-9344ab5aae24.png)

![image](https://user-images.githubusercontent.com/26074850/44422494-53b36580-a551-11e8-9935-9a259f1e4eeb.png)

2 syntax errors in install.js

**Comment by jukefr** [comment]
You probably have a very outdated version of Node far past the official current LTS release, which is `8.x.x`.

Most (somewhat outdated) distributions won't come with the current version of Node in their repositories, to give an idea, Ubuntu 16.04 currently comes with Nodejs `4.2.6` and **support for the ES `let` and `const` bindings were added around the start of version 6 of Node.**

Same concept probably applies to CentOS.

If you want to get a more up to date version of Node, I suggest you check out https://github.com/nodesource/distributions#rpminstall for an easy installation process.
To give an idea, you might want to do this :
```bash
# Remove currently installed node (package can also be called nodejs in case)
sudo rpm -e node
# Get current LTS
curl -sL https://rpm.nodesource.com/setup_8.x | bash -
```
And what you were trying to do should work.

**Comment by b-yond** [comment]
Hi Kevin,
Thanks for the response. I installed node 10 last week, as node 8 was not available. I then got this error:
Error:
  /usr/lib/node_modules/terminalizer/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
Do you have a workaround for this? The only package on CentOS 6.9 with libgtk-3.so in it is Firefox.

**Comment by jukefr** [comment]
The closest pointer I could give you is this http://itvision.altervista.org/compiling-and-installing-gtk3-in-centos6.html

Another option would be to upgrade to Centos7 if viable, it comes with gtk3 support (and systemd).

Also may I ask you what desktop environment you are currently running currently ?

**Comment by b-yond** [comment]
I heard about terminalizer through a newsletter email that Twilio sent out, and thought it was pretty awesome. I'm realizing that it requires or assumes that I have a desktop environment. This is a dev server i'm installing terminalizer on. I wanted to use the gifs as short tutorials for my dev team. I have image libraries on our web servers, so I assumed this would render a gif, and I could sent it off to my team via link or even the slack API. Maybe not though. :)

**Comment by jukefr** [comment]
Best alternative I can give without a DE is [asciinema](https://asciinema.org/), Centos probably has it available in its repositories.
What you can do is record your cast, upload it to the website, then take the link it gives you and append `.gif` to it.
For instance :
```https://asciinema.org/a/170671```
becomes
```https://asciinema.org/a/170671.gif```
And you will be show a page with a docker (so it implies you also have docker installed) command to create a gif of this cast.
The command looks like this (taken from the page above):
```docker run --rm -v $PWD:/data asciinema/asciicast2gif https://asciinema.org/a/170671.json demo.gif```
It's a nice little trick that works without a DE.

**Comment by b-yond** [comment]
Thanks Kevin, I'll check that out. Appreciate the help!

**Comment by faressoft** [comment]
Yes it doesn't support os without GUI for now. Terminalizer is still under development so there are a lot of enhancements we are doing.

Should I close the issue?

**Comment by b-yond** [comment]
Yes, you can close. Thanks Mohammad. I'll keep an eye out for updates.

**Comment by jukefr** [comment]
@faressoft you might want to add a requirements section to the README to keep people aware.

**Comment by faressoft** [comment]
We are waiting Electron to release the feature that allows us to use it without GUI
[https://github.com/electron/electron/issues/228](https://github.com/electron/electron/issues/228)
