### ISSUE TITLE
install on macos failed for 404? 

### ISSUE THREAD

**Issue by ItsFunny** [faressoft/terminalizer#185]
1454 info run electron@7.3.3 postinstall node_modules/terminalizer/node_modules/electron node install.js
1455 info run @faressoft/node-pty-prebuilt@0.9.0 postinstall { code: 0, signal: null }
1456 timing build:run:postinstall:node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt Completed in 59ms
1457 info run electron@7.3.3 postinstall { code: 1, signal: null }
1458 timing reify:rollback:createSparse Completed in 1456ms
1459 timing reify:rollback:retireShallow Completed in 0ms
1460 timing command:install Completed in 9543ms
1461 verbose stack Error: command failed
1461 verbose stack     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
1461 verbose stack     at ChildProcess.emit (node:events:527:28)
1461 verbose stack     at maybeClose (node:internal/child_process:1090:16)
1461 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
1461 verbose stack     at Socket.emit (node:events:527:28)
1461 verbose stack     at Pipe.<anonymous> (node:net:709:12)
1462 verbose pkgid electron@7.3.3
1463 verbose cwd /Users/lvcong/go/src/github.com/okex/exchain/dev/ibc
1464 verbose Darwin 21.3.0
1465 verbose argv "/opt/homebrew/Cellar/node/17.8.0/bin/node" "/opt/homebrew/bin/npm" "install" "-g" "terminalizer"
1466 verbose node v17.8.0
1467 verbose npm  v8.5.5
1468 error code 1
1469 error path /opt/homebrew/lib/node_modules/terminalizer/node_modules/electron
1470 error command failed
1471 error command sh -c node install.js
1472 error node:internal/process/promises:279
1472 error             triggerUncaughtException(err, true /* fromPromise */);
1472 error             ^
1472 error
1472 error GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v7.3.3/electron-v7.3.3-darwin-arm64.zip
1472 error     at EventEmitter.<anonymous> (/opt/homebrew/lib/node_modules/terminalizer/node_modules/got/source/as-stream.js:35:24)
1472 error     at EventEmitter.emit (node:events:527:28)
1472 error     at module.exports (/opt/homebrew/lib/node_modules/terminalizer/node_modules/got/source/get-response.js:22:10)
1472 error     at ClientRequest.handleResponse (/opt/homebrew/lib/node_modules/terminalizer/node_modules/got/source/request-as-event-emitter.js:155:5)
1472 error     at Object.onceWrapper (node:events:642:26)
1472 error     at ClientRequest.emit (node:events:539:35)
1472 error     at ClientRequest.origin.emit (/opt/homebrew/lib/node_modules/terminalizer/node_modules/@szmarczak/http-timer/source/index.js:37:11)
1472 error     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
1472 error     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
1472 error     at TLSSocket.socketOnData (node:_http_client:494:22) {
1472 error   host: 'github.com',

**Comment by mostlylikeable** [comment]
doesn't look like this package works with arm64 chip macs. there is no arm64 electron release until electron-v11.
https://www.electronjs.org/blog/apple-silicon

**Comment by ItsFunny** [comment]
close this issue ,find another way to solve this , use nvm can install terminalizer
