### ISSUE TITLE
cannot render gif

### ISSUE THREAD

**Issue by Martinits** [faressoft/terminalizer#216]
```
terminalizer render demo.yml
Error:
  Error: [71584:0128/182351.900197:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[71584:0128/182351.900246:ERROR:select_file_dialog_impl_portal.cc(243)] Failed to read portal version property


Hint:
  Use the --help option to get help about the usage
```

**Comment by hans-thomas** [comment]
Hi, I am getting this error while rendering.

```
Error: 
  Error: 
(electron:91574): Gtk-WARNING **: 17:06:37.990: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version


Hint:
  Use the --help option to get help about the usage
```

**Comment by faressoft** [comment]
@hans-thomas, please reinstall Terminalizer as a new fix has just been released.
@Martinits Could you please check if the new version fixes your issue?

**Comment by Martinits** [comment]
The freedesktop error is gone, but there's a new one:
```bash
$ terminalizer render demo.yml
Error:
  Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/terminalizer/render/frames'

Hint:
  Use the --help option to get help about the usage
```

**Comment by faressoft** [comment]
Thanks for letting me know about the new error you encountered. I've taken
note of it and will do my best to assist you in resolving this issue.

**Comment by faressoft** [comment]
I've just submitted a fix, could you please test it manually from your side to make sure it works fine?

```bash
git clone git@github.com:faressoft/terminalizer.git
gh pr checkout 226
cd terminalizer
npm install
./bin/app.js record demo
./bin/app.js render demo
```

**Comment by hans-thomas** [comment]
> @hans-thomas, please reinstall Terminalizer as a new fix has just been released. @Martinits Could you please check if the new version fixes your issue?

Hi again,
I faced this error but this time it doesn't terminate the command and just waits and I have to press `CTRL + C` to terminate the command.

```
[render] (electron:15085): Gtk-WARNING **: 10:44:45.572: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
```

**Comment by FalcoGer** [comment]
installed with npm -g install terminalizer and I get this same error when trying to render

```text
Error:
  Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/terminalizer/render/frames'

Hint:
  Use the --help option to get help about the usage
```

I created a stick bit set frames directory in that place myself, then I got this error next

```text
Error:
  Error: EACCES: permission denied, open '/usr/local/lib/node_modules/terminalizer/render/data.json'

Hint:
  Use the --help option to get help about the usage
```

I created that file and set myself as the owner, then it rendered. But I'd  rather not poke holes into my security by setting random directories owned by root as read/writable.
