### ISSUE TITLE
global configuration should be in .config/ not in home

### ISSUE THREAD

**Issue by FalcoGer** [faressoft/terminalizer#227]
According to the [XDG Specifications](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), configuration files for users should reside in `~/.config/`.

I do not enjoy having my home directory cluttered up with millions of dotfiles and dotfolders.

Currently `terminalizer init` gives this output

```text
terminalizer init
The global config directory is created at
/home/username/.terminalizer
```

Another reference [here](https://wiki.archlinux.org/title/XDG_Base_Directory#Specification).

**Comment by faressoft** [comment]
Fixed in #226
