### ISSUE TITLE
Can't Install in Ubuntu

### ISSUE THREAD

**Issue by CristoAMH** [faressoft/terminalizer#23]
I don't know what's the issue. I'll paste the err after run 'sudo npm i -g terminalizer'
Node version: v10.9.0
npm version: 6.4.0

`/usr/local/bin/terminalizer -> /usr/local/lib/node_modules/terminalizer/bin/app.js

> node-pty-prebuilt@0.7.6 install /usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js

prebuild-install WARN install EACCES: permission denied, access '/home/cristoamh/.npm'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/cristoamh/.node-gyp/10.9.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt/.node-gyp'
gyp ERR! System Linux 4.18.5-041805-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd /usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cristoamh/.npm/_logs/2018-08-24T21_36_07_802Z-debug.log
`

**Comment by faressoft** [comment]
Execute the following after replacing `faressoft` with username

```
sudo chown -R faressoft /usr/local/lib/node_modules
sudo chown -R faressoft /usr/local/bin
sudo chown -R faressoft /usr/local/share
```

Then reinstall it :)

**Comment by CristoAMH** [comment]
Perfect! Could you tell me what was the issue?

**Comment by faressoft** [comment]
These commands are required to fix the permissions to be able to install npm packages globally

**Comment by policeme** [comment]
@faressoft 
when I installed this on ubuntu it appeared this error after I ran this commands 
```
sudo chown -R faressoft /usr/local/lib/node_modules
sudo chown -R faressoft /usr/local/bin
sudo chown -R faressoft /usr/local/share
```
```
npm ERR! path ../lib/node_modules/terminalizer/bin/app.js
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink
npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/terminalizer/bin/app.js' -> '/usr/bin/terminalizer'
npm ERR!  { [Error: EACCES: permission denied, symlink '../lib/node_modules/terminalizer/bin/app.js' -> '/usr/bin/terminalizer']
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, symlink '../lib/node_modules/terminalizer/bin/app.js' -> '/usr/bin/terminalizer'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'symlink',
npm ERR!      path: '../lib/node_modules/terminalizer/bin/app.js',
npm ERR!      dest: '/usr/bin/terminalizer' },
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, symlink \'../lib/node_modules/terminalizer/bin/app.js\' -> \'/usr/bin/terminalizer\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/terminalizer/bin/app.js',
npm ERR!   dest: '/usr/bin/terminalizer' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cally/.npm/_logs/2020-04-24T08_25_41_855Z-debug.log
```

**Comment by arjun921** [comment]
@policeme It seems like your username is `cally` and not `faressoft`.
Try running this
```
sudo chown -R whoami /usr/local/lib/node_modules
sudo chown -R whoami /usr/local/bin
sudo chown -R whoami /usr/local/share
npm install -g terminalizer
```

**Comment by Zonalds** [comment]
Having same problem on Ubuntu 20.04 and nothing seems to work. Not even the gist above.
