### ISSUE TITLE
render webp format output

### ISSUE THREAD

**Issue by xiaozhuai** [faressoft/terminalizer#25]
Thanks for your great jobs, it's really cool!

For now, default shadows and margins is not transparent which not look pretty

As we know, gif format do not perform good when alpha channel exists, because gif's alpha is 0 or 1. it cannot be 0.6

If we use gif and transparent margins, we cannot Eliminating jagged edges.

That's why I suggest to add a webp format output option. It's popular, thinner than gif, and perform good with alpha channel. Then we can transparent margins.

**Comment by faressoft** [comment]
Sorry but there is no plan for this at the moment
