### ISSUE TITLE
Non-global per project dependency doesn't work with "render"

### ISSUE THREAD

**Issue by trevordmiller** [faressoft/terminalizer#27]
First, thanks for such an awesome library!

`npm install -g terminalizer`, then `terminalizer render some-recording` works as expected.

But if you do `npm install terminalizer`, then `npx terminalizer render some-recording` it hangs indefinitely without any output.

It would be cool if terminalizer also worked from the project's `node_modules` so it doesn't have to be installed globally.

**Comment by faressoft** [comment]
It is not built to be a package that you can use as a local package.
