### ISSUE TITLE
Does it work with Zsh

### ISSUE THREAD

**Issue by agarcian** [faressoft/terminalizer#3]
Is there a way to change the default shell from bash to Zsh?

**Comment by alawneh0** [comment]
#2

**Comment by faressoft** [comment]
Yes you can
[How To Support ZSH](https://github.com/faressoft/terminalizer#how-to-support-zsh)

**Comment by ryuta69** [comment]
@faressoft 

Hi, It seems not to work with zsh right now.

The image below shows command:zsh is not displaying anything, and if I initialize config with bash, it works.

<img width="588" alt="Screen Shot 2020-04-16 at 23 00 37" src="https://user-images.githubusercontent.com/41639488/79465307-207eed80-8036-11ea-8728-d5bb7a4a00d7.png">

terminalizer version : 0.7.1
zsh version : 5.8
