### ISSUE TITLE
gif generated doesn't render special characters perfectly

### ISSUE THREAD

**Issue by yittg** [faressoft/terminalizer#31]
`terminalizer` is a cool tool to record terminal and generate gif. 👍 
I use it in [my project](https://github.com/yittg/ving) to record a demonstration, and it works perfectly, record, and play, until render as an animated gif image. 
I attached the gif generated at the end of readme doc, and a screenshot what it should be at the top.
Those parts are made up of these characters `'▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'` (see [origin](https://github.com/gizak/termui/blob/fede2b0a7496f62f701fff3ea518ffd0740cf580/sparkline.go#L39)).
Can this be fixed? 😁

**Comment by faressoft** [comment]
Why you closed it? Is it invalid?

**Comment by yittg** [comment]
@faressoft figured out that it is about xterm.js and character rendering in html, not a terminalizer issue, so close it.
