### ISSUE TITLE
Can't uninstall global npm modules in terminalizer

### ISSUE THREAD

**Issue by hughrawlinson** [faressoft/terminalizer#32]
When I'm inside terminalizer, I can't uninstall npm modules. Say I have eslint installed, and then run 

```sh
npm rm -g eslint
eslint
```

I am still able to call eslint. Then, I exit terminalizer, run the same commands, and eslint is no longer on my path.

Any ideas why this might happen?

**Comment by faressoft** [comment]
What is the shell that you use ? bash, zsh, etc ?

**Comment by faressoft** [comment]
Please reopen the issue if you still need help with this.
