### ISSUE TITLE
Got Error: Xlib:  extension "NV-GLX" missing on display ":0.0". when rendering GIF

### ISSUE THREAD

**Issue by tuanlc** [faressoft/terminalizer#33]
Hello,
This is an interesting tool. Thank you for your work.

I got an error when rendering GIF:

> Error:  Xlib:  extension "NV-GLX" missing on display ":0.0".

My environment:
- Linux 4.18.14-arch1-1-ARCH
- Node: v8.11.4

Please give me some clues on this. Thanks!

**Comment by faressoft** [comment]
@tuanlc You can't render images without having a GUI
