### ISSUE TITLE
Render fails on a server without a graphics card

### ISSUE THREAD

**Issue by NickLarsenNZ** [faressoft/terminalizer#34]
I'm trying to render a recording, and after installing all the x11 dependencies, I hit this.
From reading, it appears this occurs when there is no graphics card (which is the case on this server).

```
$ terminalizer render certgen2.yml
Error:
  Error: libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so
```

Ideally I'd like to be able to render inside a Docker container - are there any plans to render with fewer dependencies?

**Comment by faressoft** [comment]
@NickLarsenNZ There is a plan to provide on cloud rendering but not for now
