### ISSUE TITLE
Terminalizer doesn't respect cwd config key

### ISSUE THREAD

**Issue by jmanuel1** [faressoft/terminalizer#39]
Terminalizer 0.6.0 seems to ignore the `cwd` in a recording configuration. That is, even when I change the key from the default, my shell still starts in the same directory that I start Terminalizer in. Currently, I've worked around this issue by using a `pwd` key. I believe the workaround succeeds because of a typo in [commands/record.js](https://github.com/faressoft/terminalizer/blob/v0.6.0/commands/record.js#L196) where `cwd` is misspelled as `pwd`, leading to the `pwd` key being used to set the working directory.

```js
  // PTY instance
  var ptyProcess = di.pty.spawn(command, commandArguments, {
    cols: config.json.cols,
    rows: config.json.rows,
    cwd: config.json.pwd, /** Typo here **/
    env: di.deepmerge(process.env, config.json.env)
  });
```

This typo, as of now, also exists on [`master`](https://github.com/faressoft/terminalizer/blob/master/commands/record.js#L196).

**Comment by faressoft** [comment]
Fixed and will be released with v0.6.1
