### ISSUE TITLE
Feature request: Global config

### ISSUE THREAD

**Issue by cbetta** [faressoft/terminalizer#4]
I want to always use zsh and I don't want to add a config file in every folder. It would be great if there was a way to set a global config, maybe in `~/.terminalizerrc` or something.

**Comment by faressoft** [comment]
You don't need to add a config file to every folder. You can just generate a config file, store it in your home directory and then use it for all your recordings via the `-c` option.

Is that solves your issue ?

**Comment by cbetta** [comment]
Ah yes that works indeed. I guess what I was looking for is a place to put a config that is picked up automatically so I don't have to pass the config in every time.

**Comment by cbetta** [comment]
My biggest issue right now actually is that I run zsh, yet terminalizer defaults to bash. It would be great if this tool either had a way for me to specify to always use zsh, or if terminalizer would just default to zsh if the user's terminal is also zsh.

**Comment by faressoft** [comment]
@cbetta I agree with you. Let's think about this and we should consider Windows OS too, since it is a cross platform tool

**Comment by LetLetLand** [comment]
i just created this alias in my `~/.zshrc` file : 
`alias record='terminalizer record --config config.yml'`
then just type record demo and terminalizer would just default to zsh.

**Comment by cbetta** [comment]
Ah yes, that is one way of doing. I like it. I guess I was looking for something to set my own default, allowing me to then use the config.yml file to override these per demo.

**Comment by faressoft** [comment]
What do you think if we provide the ability to define multiple global config files.

In case you have a Twitter, GitHub, etc accounts you can define a config file for each of them and explicitly set the number of cols and rows and other things.

We can have a directory called `.terminalizer` at the home directory, where you can define your global config files named like twitter.yml, githubreadme.yml, etc.

The question now is how to allow the user to choose from these files ?

How about:

* Pass the name as `-c cwdFileOrGlobalFileName`.
* In the option `-c` is not provided:
  * List all .yml files in the current working directory.
  * List all .yml files in the global directory.
  * Using `Inquirer.js` list.

**Comment by cbetta** [comment]
Seems overly complicated tbh. It might be something people want, but all I really want is to be able to set zsh as my default.

**Comment by faressoft** [comment]
As an alternative I can just check what is the default login shell for the current user. But the problem is you may need to change the font also ! This approach is not a good experience for the new users.

I am thinking about a way to add a new command to edit the defaults in the default editor like `vim`. What to do think about this ? Any suggestions for the name of the command.

**Comment by cbetta** [comment]
I can't speak for you, but my experience says to go for the easiest solution that is as close as possible as to how other CLI tools do things. This is why I suggested a hidden config in the home folder.

**Comment by CameronBanga** [comment]
I agree with @cbetta above. A standard, universal .terminalizerrc in my home directory would be great. Just got started with this, and can't imagine keeping separate config files in each directory.

**Comment by faressoft** [comment]
I am going to work on this feature soon. The approach is

* Adding a new command called `init` you can call it by `terminalizer init`
* The command creates a new directory called `.terminalizer` at the home directory.
* The command copies the default config file into the created directory.
* For new recording the `.terminalizer/config.yml` will be used.
* The same directory can be used also to store session related data for uploading recordings into terminalizer.com to play them online and get a link that you can share, very soon

**Comment by faressoft** [comment]
Released v0.3.0

```
terminalizer init
```
