### ISSUE TITLE
Possibility to change default visibility

### ISSUE THREAD

**Issue by kyob** [faressoft/terminalizer#45]
I can't find or there is no option to change default visibility from public to private.

**Comment by faressoft** [comment]
Go to your recording > Press the edit button > Change the visibility > Save

<img width="166" alt="Screen Shot 2019-06-05 at 22 48 34" src="https://user-images.githubusercontent.com/1908658/58989403-23893a80-87e4-11e9-9446-3923ed7c471d.png">

<img width="181" alt="Screen Shot 2019-06-05 at 22 48 40" src="https://user-images.githubusercontent.com/1908658/58989406-24ba6780-87e4-11e9-80cb-5140294fccea.png">
