### ISSUE TITLE
Terminalizer should not automatically share recordings, or make it way more clear that it does.

### ISSUE THREAD

**Issue by bradwhitfield** [faressoft/terminalizer#47]
Before using this, I read the entire readme. The impression I had afterwards was that I could share the recordings if I wanted to, since sharing is a separate command. I was annoyed to find out after using it the first time that I was incorrect in my understanding, and recordings are uploaded automatically. After re-reading the docs, it's still not clear from the readme that recordings will be automatically uploaded.

It appears things that are uploaded are not public by default, which is great. When I tried to create an account to confirm this, the site would not take my credentials, no matter how many times I reset them with different passwords. My initial test was nothing sensitive, but it was still something I did not want to upload anywhere.

With my limited experience, I like this product, especially because I can use it on Windows, Mac, and Linux, but that aspect really rubbed me the wrong way. I'll probably fork this and make a version that has no sharing functionality before I continue to test it further.

**Comment by faressoft** [comment]
@bradwhitfield This is not accurate. The tool doesn't upload anything automatically and doesn't force you to upload your recordings to just render gif images. The tool renders your recording into a gif image then it asks you to upload it. Simply just press CTRL+C to terminate the tool and skip uploading your recording.

**Comment by bradwhitfield** [comment]
I apologize for this. I misunderstood the code when I was following it last night. I'm a privacy nut, and the `https://terminalizer.com/token?token=<GUID>` links spit out by the terminal scared me a bit.

I would still for the sharing to be a more deliberate second command to enter rather than the `record` command automatically calling share in the it's `done` function.

**Comment by dciancu** [comment]
I totally agree with @bradwhitfield, the link along with the prompt scared me as well and made me go ahead on the official site to check for my recording if it got uploaded as I hit enter at the prompt.

@faressoft Would vote for a prompt like: `Would you like to upload your recording to https://terminalizer.com? yes/no [yes]` (And you can keep the default answer to `yes` if you would like to promote the sharing service, though I would argue for a `no` default answer.).

**Comment by faressoft** [comment]
@bradwhitfield @dciancu
I've just published a new version to enhance the user experience.

- Showing a prompt message to ask the user to share or not
- Option to skip showing the prompt and skip sharing (for people who use the tool in an automated way)

<img width="513" alt="prompt" src="https://user-images.githubusercontent.com/1908658/79669729-e2143a80-81bd-11ea-8154-69eb30d64bcf.png">
 
<img width="736" alt="skip-sharing" src="https://user-images.githubusercontent.com/1908658/79669731-e2acd100-81bd-11ea-92f2-a9cd02402d8e.png">

**Comment by bradwhitfield** [comment]
This is great! Thank you for adding this prompt and flag! This is much more clear to me now.
