### ISSUE TITLE
Sign up - Error

### ISSUE THREAD

**Issue by andrewpsp** [faressoft/terminalizer#50]
When attempting to simply sign up as new user after filling out the form returns 500. 
<img width="1258" alt="Screen Shot 2019-03-14 at 3 50 05 PM" src="https://user-images.githubusercontent.com/1671454/54390667-163f3280-4671-11e9-8f02-bebf82db479a.png">

**Comment by Rishats** [comment]
Same problem, recording doesn't work(

**Comment by lakhujanivijay** [comment]
same here

**Comment by faressoft** [comment]
The issue is fixed
