### ISSUE TITLE
Never used your service, but am logged in on your website as someone else

### ISSUE THREAD

**Issue by gaggle** [faressoft/terminalizer#53]
Hi,

Just to say I've not used your service before, but I appear logged in when I visit your docs website at: https://terminalizer.com/docs

I appear logged in as user "jortpolderdijk", and can see a recording made 4 days ago.

![Screenshot from 2019-05-03 08-45-21](https://user-images.githubusercontent.com/2316447/57122922-01814000-6d80-11e9-9e40-4449d9d0bf9e.png)

![Screenshot from 2019-05-03 08-44-57](https://user-images.githubusercontent.com/2316447/57122923-01814000-6d80-11e9-8c90-fdf0d58eb71e.png)

At a glance this seemed so odd I wanted to reach out with this information in case you also find it odd.

**Comment by faressoft** [comment]
Fixed. The page (html) was cached but you are not actually logged in
