### ISSUE TITLE
Config using default terminal colors

### ISSUE THREAD

**Issue by TaylorZowtuk** [faressoft/terminalizer#60]
I'm working on showing the running of a project where it is important that the colors displayed on the terminal are accurate to the default terminal color settings (ie. i dont want a fancy config color theme). Is there a way to specify not to use a theme and rather use the default terminal settings?

**Comment by faressoft** [comment]
Unfortunately it is not possible. I suggest to find a way to export the colors scheme of the terminal and find an online website to convert these colors into hexa colors  format

**Comment by TaylorZowtuk** [comment]
Alright thanks!
