### ISSUE TITLE
sharing a recording should be optional

### ISSUE THREAD

**Issue by devinburnette** [faressoft/terminalizer#69]
What if instead of including the sharing dialogue in the recordings done function, it could be optionally executed with a command line flag `--share`. I noticed that `terminalizer share <recording>` is also already a thing so maybe even just move out that logic altogether? 

Curious what that would look like for folks looking to automate their own systems to share the recordings.

**Comment by faressoft** [comment]
I've just published a new version to enhance the user experience.

- Showing a prompt message to ask the user to share or not
- Option to skip showing the prompt and skip sharing (for people who use the tool in an automated way)

<img width="513" alt="prompt" src="https://user-images.githubusercontent.com/1908658/79669729-e2143a80-81bd-11ea-8154-69eb30d64bcf.png">
 
<img width="736" alt="skip-sharing" src="https://user-images.githubusercontent.com/1908658/79669731-e2acd100-81bd-11ea-92f2-a9cd02402d8e.png">
