### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by weylermaldonado** [faressoft/terminalizer#7]
When I run the install command (with sudo), get this:

```
usr/local/bin/terminalizer -> /usr/local/lib/node_modules/terminalizer/bin/app.js

> node-pty-prebuilt@0.7.3 install /usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js

prebuild-install WARN install EACCES: permission denied, mkdir '/usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt/build'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt/build'
gyp ERR! System Linux 4.15.0-29-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/weyler/.npm/_logs/2018-07-29T00_58_39_796Z-debug.log
```

Any idea? I use Ubuntu 16.04, and my terminal have zsh, and I tried with all the readme's fixes but didn't work.

Send help.

**Comment by faressoft** [comment]
It seems something not related to Terminalizer.

But anyway, try this and don't forget to change the `userName`.

```bash
chown -R userName /usr/local/lib/node_modules
chown -R userName /usr/local/bin
chown -R userName /usr/local/share
```

**Comment by weylermaldonado** [comment]
Didn't work with the chown commands. I researched a bit and seems it's someting with electron, I don't know much of electron, but I fixed with this command:

`sudo npm install -g terminalizer --unsafe-perm=true --allow-root`

However, thanks a lot ;)

**Comment by faressoft** [comment]
Enjoy :)

**Comment by j1elo** [comment]
Changing ownership of contents inside `/usr` is **not** a good solution. That's a system directory and it should be owned by root.

Solution by @weylermaldonado works properly by [allowing root operation](https://stackoverflow.com/a/46439404). This should be shown in the [Installation instructions](https://terminalizer.com/install) instead of leaving buried in a closed issue.
