### ISSUE TITLE
Recording format documentation

### ISSUE THREAD

**Issue by ikhosravi** [faressoft/terminalizer#71]
Hi,
Is there any documentation of how recording is done and the recording file structure?
 In case a third party would wants to save it's terminal session activities in terminalizer format without using terminalizer record functionality.
In other words I want to integrate terminalizer into another session recording application.
Thanks in advance

**Comment by faressoft** [comment]
The output file is a YAML file with two keys

- config: check [Documentation](https://github.com/faressoft/terminalizer#configurations)
- records:
  - delay: in ms
  - content: stdin+stdout+stderr

**Comment by Nakilon** [comment]
I wonder how to emulate the rewriting of the whole screen or changes at specific coordinates. I'm not familiar with how terminals do it via the stdout stream so examples would be cool.
