### ISSUE TITLE
Why does it need libnss?

### ISSUE THREAD

**Issue by DannyBen** [faressoft/terminalizer#77]
Running render generates this error on Ubuntu:

```
$ terminalizer render 1.yml
Error:
  Error: /home/vagrant/.config/yarn/global/node_modules/electron/dist/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

Why is libnss3 needed?

Then, after installing libnss3, it complained about another missing library: `libgtk-3.so`.

This seems to have way too many dependencies.

**Comment by faressoft** [comment]
Are using gui ubunu? otherwise your can't render.

**Comment by DannyBen** [comment]
> Are using gui ubunu? otherwise your can't render.

Oh... that's a firm no 😈 
Thanks for responding.
