### ISSUE TITLE
Add "terminal-recording" topic to this repo

### ISSUE THREAD

**Issue by katrinleinweber** [faressoft/terminalizer#8]
As an educator, I'd like to be able to advertise the concept of creating animations from the terminal, without:

a) recommending a particular software, 
b) collecting a bunch of individual links.

Thus, https://github.com/topics/terminal-recording is a perfect page to send learners to, to explore the topic further and find a tool that suits them.

How about `terminalizer` joins that small club and also uses the GitHup topic `terminal-recording`?

**Comment by faressoft** [comment]
I Will consider this, thanks :)
