### ISSUE TITLE
WSL 2: Socket Hangup

### ISSUE THREAD

**Issue by AlexanderAllen** [faressoft/terminalizer#82]
![image](https://user-images.githubusercontent.com/14018885/73386650-34b81780-429d-11ea-8613-db78c0e8e32b.png)

After entering the title and description prompts, I get the following error:

```
Error:
  Error: socket hang up
```

Screenshot provided.

Running inside Windows Subsystem for Linux, version 2.

WSL distribution: Ubuntu 18.04

Node version:

```
2020-01-29-01:36PM wsl@Ubuntu-18.04:~$ node --version
v12.14.1
```

**Comment by AlexanderAllen** [comment]
Probably mentioned on installation notes:

![image](https://user-images.githubusercontent.com/14018885/73386968-c2940280-429d-11ea-9fd2-1849881df7d1.png)

**Comment by AlexanderAllen** [comment]
Closing. Just realized that terminalizer is running Electron, and Electron is not meant to run on WSL, period. Thanks.

**Comment by nick4fake** [comment]
@AlexanderAllen why do you think Electron is not meant to run on WSL? You can literally run GUI applications in WSL
