### ISSUE TITLE
Default Recording Share Permission is Public

### ISSUE THREAD

**Issue by shmcfarl** [faressoft/terminalizer#91]
I am not sure that all users of Terminalizer understand that when they complete a recording that their file is shown as 'public' on the terminalizer.com "Explore" page. The documentation needs to stated that this is the default behavior (add it to the install page) and it there should be a global config option to change the default behavior to "private".

I have seen some recordings with token/login info which is very bad.

If this is already a setting now, please let me know.

**Comment by faressoft** [comment]
It is not true that when you complete a recording it will be shared on the website. The tool asked the user to share but that also requires registration on the website and granting the tool an access token. So sharing something by mistake is very unlikely to happen.
