### ISSUE TITLE
Render is failing

### ISSUE THREAD

**Issue by maricn** [faressoft/terminalizer#96]
Command I'm trying:
```
terminalizer render ../github-pr-demo.yml
```

This is the error:
```
Error: 
  Error: [5282:0421/171616.676227:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command


Hint:
  Use the --help option to get help about the usage
```

I am on MXLinux, I use default config, terminalizer version 0.7.2.
I'm on `sakura` terminal emulator, version 3.6.0. I've tried `xfce4-terminal` and `alacritty`, same results.
I'm using NodeJS version v12.14.1, tried v12.16.2 as well.

**Comment by mStirner** [comment]
Same here. Node version 12.16.2 too.
Distribution is Ubuntu 18.04 LTS

**Comment by mStirner** [comment]
@maricn I found a error related to electron and "buffer_manager.cc".
Have you a GPU installed, if yes NVIDIA or ATI/AMD ?

```sudo lshw -C display
```

```
  *-display                 
       Beschreibung: VGA compatible controller
       Produkt: Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
       Hersteller: Advanced Micro Devices, Inc. [AMD/ATI]
       Physische ID: 0
       Bus-Informationen: pci@0000:01:00.0
       Version: 00
       Breite: 64 bits
       Takt: 33MHz
       Fähigkeiten: pm pciexpress msi vga_controller bus_master cap_list rom
       Konfiguration: driver=radeon latency=0
       Ressourcen: irq:47 memory:e0000000-efffffff memory:f7e00000-f7e3ffff ioport:e000(Größe=256) memory:c0000-dffff

```

**Comment by maricn** [comment]
@mStirner Nice catch!

I'm not using GPU, I'm on Lenovo X1 Carbon Gen 7 with Intel UHD 620. Details below.

However, it seems to be the cause of the problem. I've tried editing https://github.com/faressoft/terminalizer/blob/master/commands/render.js#L121 to include `--disable-gpu` and it works now. It did rendering of 343 frames in 50s but merging was painfully slow - 40 minutes to merge 343 frames, but at least it doesn't crash.

There's nothing reported on electron project https://github.com/electron/electron/issues?q=sort%3Aupdated-desc+GL_INVALID_OPERATION+buffer_manager

`lspci|grep VGA`:
```
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (Whiskey Lake) (rev 02)
```

`lshw -C display`:
```
  *-display                 
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:158 memory:e2000000-e2ffffff memory:c0000000-dfffffff ioport:2000(size=64) memory:c0000-dffff
```

I can't invest into fixing this issue "properly" now, but I can submit a PR to at least retry rendering without GPU if it fails the first time.

**Comment by bk211** [comment]
Hello, I have encounter the same issue, here's my config Lenove Y720 archlinux, with konsole terminal 
First time it failed with my intel HD card 
> lspci | grep VGA
> 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
> 01:00.0 VGA compatible controller: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1)

here is the same error message 

> Error: 
  Error: [8791:0430/222654.403624:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command



when I switched to nvidia, it does render properly now, however the process is quite slow, my version is the last one 0.7.2
Fixe probably not integrated yet to the current version?

**Comment by maricn** [comment]
@bk211 I'm in no means an expert, but from my own brief experience, the rendering part is fast and can use GPU to make it faster. The following ffmpeg merging part is anyways slower, and afaik is not related to this error.

You can try the build from the linked PR if you're stuck at that error during rendering part. However it's strange that your attempt using nvidia GPU gets the same error and ignores it to finish successfully.

**Comment by miraclx** [comment]
Here's another idea, maybe we shouldn't act on data streamed into `stderr` immediately. These could be mere warnings. Like the one about the GPU.

_(yet to be tested)_ but I think that GPU warning wouldn't have affected the electron process itself in any way. Chromium would've fallen back to skipping the use of a GPU.

Best to let the process run it's course and only after we can check that we have a non-zero return code, should we reject the rendering promise.

**Comment by joaopgrassi** [comment]
Just want to leave here that I also face the same issue. Running on Linux Mint 20 (ulyana). My laptop has a discrete NVIDIA card which is disabled, and I just use the Intel UHD one.

**Comment by miraclx** [comment]
@joaopgrassi, does #97 help?

**Comment by joaopgrassi** [comment]
Hey @miraclx !
Yes it works with #97. Just checked it out and running locally I can now render it just fine.

**Comment by jjmachan** [comment]
thanks @maricn and @maricn , was facing the same issue and checkout the PR locally and it worked.
Thanks a mill :tada:
